# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 95a2f83ae0528bb265be2901a7f3e4ab8a5113321b857436b4883a09c728a4e0389f4515d716500358932131e0b2464d78ee868850ec933f4bf503cae0510523

test:
  secret_key_base: 860d6769e0b1f86fa75324897d74093c18680926d7e1b0e65d865cfecd7b3903a98d680ea6fc5c2853aa03a358cd7328dea832a7a2279814976fa763c6b00344

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
